// Tests for lib/dashboard.mjs: deterministic openspec/ overview generation.
// Fixture trees are built in fs.mkdtempSync temp dirs; assertions are golden
// byte-for-byte on the rendered note plus idempotency and base-seeding behavior.

import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { fileURLToPath } from "node:url";

import {
  collectChanges,
  collectSpecs,
  renderDashboard,
  dashboard,
  DashboardError,
} from "../lib/dashboard.mjs";

// --- fixture helpers -----------------------------------------------------

function mkRoot() {
  return fs.mkdtempSync(path.join(os.tmpdir(), "opsx-dashboard-"));
}

function writeFile(root, relPath, content) {
  const full = path.join(root, relPath);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content);
}

function readFile(root, relPath) {
  return fs.readFileSync(path.join(root, relPath), "utf8");
}

const ASSET_BASE = fs.readFileSync(
  path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "assets", "dashboard.base"),
  "utf8",
);

const SPEC_1REQ = `---
type: spec
capability: gadgets
---

# gadgets Specification

## Purpose

Gadgets.

## Requirements

### Requirement: Gadgets exist
Body.

#### Scenario: it works
- **WHEN** a
- **THEN** b
`;

const SPEC_2REQ = `---
type: spec
capability: widgets
---

# widgets Specification

## Purpose

Widgets.

## Requirements

### Requirement: Widgets exist
Body.

#### Scenario: it works
- **WHEN** a
- **THEN** b

### Requirement: Widgets endure
Body.

#### Scenario: it endures
- **WHEN** c
- **THEN** d
`;

const TASKS_PARTIAL = `---
type: tasks
---

## 1. Group

- [x] 1.1 done
- [x] 1.2 done
- [ ] 1.3 open
`;

const TASKS_COMPLETE = `---
type: tasks
---

## 1. Group

- [x] 1.1 done
- [x] 1.2 done
`;

function seed(root) {
  writeFile(root, "openspec/specs/widgets/spec.md", SPEC_2REQ);
  writeFile(root, "openspec/specs/gadgets/spec.md", SPEC_1REQ);
  writeFile(root, "openspec/changes/add-widgets/proposal.md", "## Why\nWidgets.\n");
  writeFile(root, "openspec/changes/add-widgets/tasks.md", TASKS_PARTIAL);
  writeFile(root, "openspec/changes/ship-gadgets/proposal.md", "## Why\nGadgets.\n");
  writeFile(root, "openspec/changes/ship-gadgets/tasks.md", TASKS_COMPLETE);
  writeFile(root, "openspec/changes/archive/2026-01-02-add-gizmos/proposal.md", "## Why\nGizmos.\n");
  writeFile(root, "openspec/changes/archive/2026-01-02-add-gizmos/tasks.md", TASKS_COMPLETE);
  writeFile(root, "openspec/obsidian.yaml", "features:\n  dashboard: true\n");
}

const GOLDEN = `---
type: dashboard
tags: [openspec, type/dashboard]
aliases: ["openspec dashboard"]
---

# OpenSpec Dashboard

<!-- Generated by \`openspec-obsidian dashboard\`. Re-run to refresh; do not edit by hand. -->

## Active changes

- [[changes/add-widgets/proposal|add-widgets]] — 2/3 tasks, in progress
- [[changes/ship-gadgets/proposal|ship-gadgets]] — 2/2 tasks, complete

## Capabilities

- [[specs/gadgets/spec|gadgets]] — 1 requirement
- [[specs/widgets/spec|widgets]] — 2 requirements

## Archive

- [[changes/archive/2026-01-02-add-gizmos/proposal|add-gizmos]] — 2026-01-02
`;

// ==========================================================================
// collectChanges / collectSpecs: discovery + progress + counts
// ==========================================================================

test("collectChanges reports active progress and archived history; collectSpecs counts requirements", () => {
  const root = mkRoot();
  try {
    seed(root);

    const { active, archived } = collectChanges(root);
    assert.deepEqual(
      active.map((c) => c.id),
      ["add-widgets", "ship-gadgets"],
      "active sorted by id",
    );
    assert.deepEqual(active[0], {
      id: "add-widgets",
      done: 2,
      open: 1,
      total: 3,
      complete: false,
      hasProposal: true,
    });
    assert.deepEqual(active[1], {
      id: "ship-gadgets",
      done: 2,
      open: 0,
      total: 2,
      complete: true,
      hasProposal: true,
    });

    assert.equal(archived.length, 1);
    assert.deepEqual(archived[0], {
      dir: "2026-01-02-add-gizmos",
      id: "add-gizmos",
      date: "2026-01-02",
      hasProposal: true,
    });

    const specs = collectSpecs(root);
    assert.deepEqual(specs, [
      { capability: "gadgets", requirementCount: 1 },
      { capability: "widgets", requirementCount: 2 },
    ]);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

// ==========================================================================
// renderDashboard: empty tree yields explicit placeholders
// ==========================================================================

test("renderDashboard emits placeholders for an empty tree", () => {
  const md = renderDashboard({ active: [], archived: [], specs: [] });
  assert.match(md, /## Active changes\n\n_No active changes\._\n/);
  assert.match(md, /## Capabilities\n\n_No capabilities yet\._\n/);
  assert.match(md, /## Archive\n\n_Nothing archived yet\._\n/);
});

test("renderDashboard singularizes a one-requirement capability and links proposals", () => {
  const md = renderDashboard({
    active: [{ id: "add-x", done: 0, open: 2, total: 2, complete: false, hasProposal: true }],
    archived: [],
    specs: [{ capability: "x", requirementCount: 1 }],
  });
  assert.match(md, /- \[\[changes\/add-x\/proposal\|add-x\]\] — 0\/2 tasks, in progress\n/);
  assert.match(md, /- \[\[specs\/x\/spec\|x\]\] — 1 requirement\n/);
});

// ==========================================================================
// dashboard(): golden write + byte-identical rerun + base seeding
// ==========================================================================

test("dashboard writes a golden note, seeds the base, and re-runs byte-identically", async (t) => {
  const root = mkRoot();
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  seed(root);

  const first = dashboard(root);
  assert.equal(first.md, GOLDEN, "returned markdown matches golden");
  assert.equal(readFile(root, "openspec/dashboard.md"), GOLDEN, "written note matches golden");
  assert.deepEqual(first.written, ["dashboard.md", "dashboard.base"]);
  assert.deepEqual(first.skipped, []);

  // Base is seeded from the shipped asset.
  assert.equal(readFile(root, "openspec/dashboard.base"), ASSET_BASE);
  // Output stays in the tracked vault body, never under the gitignored .obsidian/.
  assert.ok(!fs.existsSync(path.join(root, "openspec", ".obsidian", "dashboard.md")));

  // Second run: note re-written identically, base now preserved (skip).
  const second = dashboard(root);
  assert.equal(second.md, GOLDEN);
  assert.equal(readFile(root, "openspec/dashboard.md"), GOLDEN, "rerun is byte-identical");
  assert.deepEqual(second.written, ["dashboard.md"]);
  assert.deepEqual(second.skipped, ["dashboard.base"]);
});

// ==========================================================================
// dashboard(): base preservation vs --force
// ==========================================================================

test("dashboard preserves an existing base without --force and overwrites it with --force", async (t) => {
  const root = mkRoot();
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  seed(root);
  writeFile(root, "openspec/dashboard.base", "# customized by the user\n");

  const kept = dashboard(root);
  assert.deepEqual(kept.skipped, ["dashboard.base"]);
  assert.equal(readFile(root, "openspec/dashboard.base"), "# customized by the user\n");

  const forced = dashboard(root, { force: true });
  assert.deepEqual(forced.written, ["dashboard.md", "dashboard.base"]);
  assert.equal(readFile(root, "openspec/dashboard.base"), ASSET_BASE);
});

// ==========================================================================
// dashboard(): dry-run writes nothing
// ==========================================================================

test("dashboard --dry-run writes no files", async (t) => {
  const root = mkRoot();
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  seed(root);

  const res = dashboard(root, { dryRun: true });
  assert.equal(res.md, GOLDEN, "dry-run still returns the planned markdown");
  assert.deepEqual(res.written, []);
  assert.ok(!fs.existsSync(path.join(root, "openspec", "dashboard.md")));
  assert.ok(!fs.existsSync(path.join(root, "openspec", "dashboard.base")));
});

// ==========================================================================
// dashboard(): missing openspec/ is a hard error
// ==========================================================================

test("dashboard throws DashboardError when openspec/ is absent", () => {
  const root = mkRoot();
  try {
    assert.throws(() => dashboard(root), DashboardError);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

// ==========================================================================
// dashboard(): disabled feature is an actionable error
// ==========================================================================

test("dashboard throws DashboardError naming the toggle when the feature is disabled", (t) => {
  const root = mkRoot();
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  seed(root);
  fs.rmSync(path.join(root, "openspec", "obsidian.yaml")); // feature not enabled

  assert.throws(() => dashboard(root), (err) => {
    assert.ok(err instanceof DashboardError);
    assert.match(err.message, /openspec\/obsidian\.yaml/);
    assert.match(err.message, /dashboard: true/);
    return true;
  });
  assert.ok(!fs.existsSync(path.join(root, "openspec", "dashboard.md")), "writes nothing when disabled");
});
