// Tests for lib/hubs.mjs: deterministic per-change hub-note generation, self-scoped
// stale cleanup, dry-run, and inertness to backfill/dashboard. Fixture trees are
// built in fs.mkdtempSync temp dirs; assertions are golden byte-for-byte on the
// rendered note plus idempotency, cleanup, and non-interference behavior.

import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";

import { collectHubs, renderHub, hubs, HubsError } from "../lib/hubs.mjs";
import { backfill } from "../lib/backfill.mjs";
import { collectChanges, renderDashboard } from "../lib/dashboard.mjs";

// --- fixture helpers -----------------------------------------------------

function mkRoot() {
  return fs.mkdtempSync(path.join(os.tmpdir(), "opsx-hubs-"));
}

function writeFile(root, relPath, content) {
  const full = path.join(root, relPath);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content);
}

function readFile(root, relPath) {
  return fs.readFileSync(path.join(root, relPath), "utf8");
}

// Seed an active change `add-foo` with all four linkable artifacts and 1/2 tasks.
function seedFoo(root) {
  writeFile(root, "openspec/config.yaml", "x: 1\n");
  writeFile(root, "openspec/changes/add-foo/proposal.md", "---\ntype: proposal\n---\n");
  writeFile(root, "openspec/changes/add-foo/design.md", "---\ntype: design\n---\n");
  writeFile(
    root,
    "openspec/changes/add-foo/tasks.md",
    "---\ntype: tasks\n---\n\n- [x] 1.1 done\n- [ ] 1.2 todo\n",
  );
  writeFile(
    root,
    "openspec/changes/add-foo/specs/foo/spec.md",
    "---\ntype: spec-delta\n---\n## ADDED Requirements\n",
  );
}

const GOLDEN_FOO = `---
type: hub
change: add-foo
tags: [openspec, type/hub, capability/foo]
aliases: ["add-foo hub"]
---

# add-foo

<!-- Generated by \`openspec-obsidian hubs\`. Re-run to refresh; do not edit by hand. -->

**Progress:** 1/2 tasks, in progress

## Artifacts

- [[changes/add-foo/proposal|add-foo proposal]]
- [[changes/add-foo/design|add-foo design]]
- [[changes/add-foo/tasks|add-foo tasks]]
- [[changes/add-foo/specs/foo/spec|add-foo foo delta]]
`;

// ==========================================================================
// hubs(): golden write + byte-identical rerun (task 1.2)
// ==========================================================================

test("hubs writes a golden hub note and re-runs byte-identically", (t) => {
  const root = mkRoot();
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  seedFoo(root);

  const r1 = hubs(root);
  assert.deepEqual(r1, { written: ["changes/add-foo.md"], removed: [] });
  assert.equal(readFile(root, "openspec/changes/add-foo.md"), GOLDEN_FOO);

  const first = readFile(root, "openspec/changes/add-foo.md");
  hubs(root);
  assert.equal(readFile(root, "openspec/changes/add-foo.md"), first, "second run byte-identical");
});

// ==========================================================================
// renderHub: progress + link variants (pure)
// ==========================================================================

test("renderHub renders complete/no-task states and omits missing artifacts", () => {
  const complete = renderHub({
    id: "c",
    done: 3,
    open: 0,
    total: 3,
    complete: true,
    hasProposal: true,
    hasDesign: false,
    hasTasks: true,
    deltaCaps: [],
  });
  assert.match(complete, /\*\*Progress:\*\* 3\/3 tasks, complete/);
  assert.match(complete, /- \[\[changes\/c\/proposal\|c proposal\]\]/);
  assert.match(complete, /- \[\[changes\/c\/tasks\|c tasks\]\]/);
  assert.ok(!complete.includes("c/design"), "omits absent design link");

  const empty = renderHub({
    id: "d",
    done: 0,
    open: 0,
    total: 0,
    complete: false,
    hasProposal: false,
    hasDesign: false,
    hasTasks: false,
    deltaCaps: [],
  });
  assert.match(empty, /\*\*Progress:\*\* no tasks/);
  assert.match(empty, /_No artifacts\._/);
});

test("renderHub tags and links every delta capability, sorted", () => {
  const hub = collectHubsFixture();
  const md = renderHub(hub);
  assert.match(md, /tags: \[openspec, type\/hub, capability\/a, capability\/b\]/);
  const aIdx = md.indexOf("specs/a/spec");
  const bIdx = md.indexOf("specs/b/spec");
  assert.ok(aIdx > 0 && bIdx > aIdx, "delta links in sorted order");
});

function collectHubsFixture() {
  return {
    id: "multi",
    done: 0,
    open: 1,
    total: 1,
    complete: false,
    hasProposal: true,
    hasDesign: false,
    hasTasks: true,
    deltaCaps: ["a", "b"],
  };
}

// ==========================================================================
// collectHubs: discovery + progress + delta caps, sorted, excludes archive
// ==========================================================================

test("collectHubs enumerates active changes with progress and delta caps", () => {
  const root = mkRoot();
  seedFoo(root);
  writeFile(root, "openspec/changes/add-bar/tasks.md", "---\ntype: tasks\n---\n\n- [x] 1.1\n");
  writeFile(root, "openspec/changes/archive/2026-01-01-old/proposal.md", "---\n---\n");

  const got = collectHubs(root);
  fs.rmSync(root, { recursive: true, force: true });

  assert.deepEqual(
    got.map((h) => h.id),
    ["add-bar", "add-foo"],
    "sorted by id, archive excluded",
  );
  const foo = got.find((h) => h.id === "add-foo");
  assert.deepEqual(
    { done: foo.done, total: foo.total, complete: foo.complete, caps: foo.deltaCaps },
    { done: 1, total: 2, complete: false, caps: ["foo"] },
  );
  const bar = got.find((h) => h.id === "add-bar");
  assert.equal(bar.complete, true);
  assert.deepEqual(bar.deltaCaps, []);
});

// ==========================================================================
// Stale cleanup (task 2.1)
// ==========================================================================

test("hubs removes a stale hub note but preserves a non-hub note", (t) => {
  const root = mkRoot();
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  seedFoo(root);
  // A leftover hub note whose change dir is gone (e.g. archived).
  writeFile(root, "openspec/changes/archive/2026-01-01-gone/proposal.md", "---\n---\n");
  writeFile(
    root,
    "openspec/changes/gone.md",
    '---\ntype: hub\nchange: gone\n---\n\n# gone\n',
  );
  // A user's own note that is NOT a hub — must never be touched.
  const userNote = "---\ntype: note\n---\n\n# my notes\n";
  writeFile(root, "openspec/changes/notes.md", userNote);

  const r = hubs(root);
  assert.deepEqual(r.written, ["changes/add-foo.md"]);
  assert.deepEqual(r.removed, ["changes/gone.md"]);
  assert.equal(fs.existsSync(path.join(root, "openspec/changes/gone.md")), false, "stale hub gone");
  assert.equal(readFile(root, "openspec/changes/notes.md"), userNote, "non-hub note preserved");
  assert.ok(fs.existsSync(path.join(root, "openspec/changes/add-foo.md")), "active hub written");
});

test("hubs --dry-run previews writes and removals without touching the vault", (t) => {
  const root = mkRoot();
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  seedFoo(root);
  writeFile(root, "openspec/changes/gone.md", "---\ntype: hub\nchange: gone\n---\n");

  const before = fs.readdirSync(path.join(root, "openspec/changes")).sort();
  const goneBytes = readFile(root, "openspec/changes/gone.md");

  const r = hubs(root, { dryRun: true });
  assert.deepEqual(r.written, ["changes/add-foo.md"]);
  assert.deepEqual(r.removed, ["changes/gone.md"]);

  const after = fs.readdirSync(path.join(root, "openspec/changes")).sort();
  assert.deepEqual(after, before, "no files created or deleted");
  assert.equal(fs.existsSync(path.join(root, "openspec/changes/add-foo.md")), false, "nothing written");
  assert.equal(readFile(root, "openspec/changes/gone.md"), goneBytes, "stale hub untouched");
});

test("hubs is a no-op with no active changes", (t) => {
  const root = mkRoot();
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  writeFile(root, "openspec/config.yaml", "x: 1\n");
  const r = hubs(root);
  assert.deepEqual(r, { written: [], removed: [] });
});

test("hubs throws HubsError when openspec/ is absent", () => {
  const root = mkRoot();
  assert.throws(() => hubs(root), (e) => e instanceof HubsError && /no openspec\//.test(e.message));
  fs.rmSync(root, { recursive: true, force: true });
});

// ==========================================================================
// Inertness to the rest of the toolchain (task 3.2)
// ==========================================================================

test("backfill leaves a hub note byte-for-byte unchanged", (t) => {
  const root = mkRoot();
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  seedFoo(root);
  hubs(root);
  const hubBytes = readFile(root, "openspec/changes/add-foo.md");

  const res = backfill(root);
  assert.ok(
    !res.written.includes("changes/add-foo.md"),
    "hub note is not treated as a backfill artifact",
  );
  assert.equal(readFile(root, "openspec/changes/add-foo.md"), hubBytes, "hub note unchanged");
});

test("dashboard discovery is identical with and without hub notes present", (t) => {
  const root = mkRoot();
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  seedFoo(root);

  const before = renderDashboard({ ...collectChanges(root), specs: [] });
  hubs(root); // materialize hub notes beside the change dirs
  const after = renderDashboard({ ...collectChanges(root), specs: [] });

  assert.equal(after, before, "hub notes do not alter dashboard output");
});
