// Generate and maintain a single release-anchored changelog note in the vault
// (openspec/changelog.md) from Conventional Commit history between release tags.
// Prepend-only, newest-first; existing sections are immutable. Self-anchored: the
// previous release is the version in the topmost "## v" heading of the note (no
// GitHub API). Deterministic — identical repo state yields byte-identical output.
//
// This is the only command that shells out to git (tags/log are unreachable from
// node:fs); git access is isolated in thin execFileSync wrappers. All parsing and
// rendering helpers are pure and exported for tests; bin/cli.mjs dispatches changelog().

import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";

export class ChangelogError extends Error {}

const US = "\x1f"; // unit separator between fields
const RS = "\x1e"; // record separator between commits
const BUCKET_ORDER = ["Breaking", "Features", "Fixes", "Internal"];

// Frontmatter + header for a fresh note (no sections yet).
const HEAD_LINES = [
  "---",
  "type: changelog",
  'title: "Changelog"',
  "tags: [openspec, type/changelog]",
  'aliases: ["Changelog"]',
  "---",
  "",
  "# Changelog",
  "",
  "<!-- Generated by `openspec-obsidian changelog`. Sections are prepend-only; do not edit by hand. -->",
];
export const EMPTY_NOTE = HEAD_LINES.join("\n") + "\n";

// --- pure helpers ------------------------------------------------------------

// The tag named by the topmost "## v<version>" heading of an existing note, or
// null when the note is absent or has no version headings.
export function parseAnchor(noteText) {
  if (!noteText) return null;
  const m = noteText.match(/^## (v\S+)/m);
  return m ? m[1] : null;
}

// Bucket a commit from its message: a "!" before the subject's colon or a
// "BREAKING CHANGE" footer -> Breaking; feat -> Features; fix -> Fixes; every
// other commit (including non-conventional subjects) -> Internal.
export function bucketOf({ subject, body = "" }) {
  const m = subject.match(/^(\w+)(?:\([^)]*\))?(!)?:/);
  const breaking = (m && m[2] === "!") || /(^|\n)BREAKING[ -]CHANGE/.test(body);
  if (breaking) return "Breaking";
  if (m && m[1] === "feat") return "Features";
  if (m && m[1] === "fix") return "Fixes";
  return "Internal";
}

// Map change id -> dated archive dir name for every dir under
// openspec/changes/archive/ named "YYYY-MM-DD-<id>".
export function archiveIndex(root) {
  const dir = path.join(root, "openspec", "changes", "archive");
  const map = {};
  if (!fs.existsSync(dir)) return map;
  for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
    if (!ent.isDirectory()) continue;
    const m = ent.name.match(/^\d{4}-\d{2}-\d{2}-(.+)$/);
    if (m) map[m[1]] = ent.name;
  }
  return map;
}

function escapeRe(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// If a token in `subject` equals an archived change id, wikilink that token to
// the archived proposal; otherwise return the subject unchanged. Longest ids
// win so a shorter id never matches inside a longer one.
export function linkSubject(subject, index) {
  const ids = Object.keys(index).sort((a, b) => b.length - a.length);
  for (const id of ids) {
    const re = new RegExp(`(?<![\\w-])${escapeRe(id)}(?![\\w-])`);
    if (re.test(subject)) {
      return subject.replace(re, `[[changes/archive/${index[id]}/proposal|${id}]]`);
    }
  }
  return subject;
}

// Render a "## <release> — <date>" section as an array of lines (no leading or
// trailing blank lines). Commits keep git-log order within each bucket; empty
// buckets are omitted.
export function renderSection(release, date, commits, index = {}) {
  const groups = { Breaking: [], Features: [], Fixes: [], Internal: [] };
  for (const c of commits) groups[bucketOf(c)].push(linkSubject(c.subject, index));
  const lines = [`## ${release} — ${date}`];
  for (const b of BUCKET_ORDER) {
    if (groups[b].length === 0) continue;
    lines.push("", `### ${b}`, "");
    for (const s of groups[b]) lines.push(`- ${s}`);
  }
  return lines;
}

// Prepend a rendered section (array of lines) to a note, preserving the head and
// every existing section byte-for-byte. Deterministic trailing newline.
export function prependSection(noteText, sectionLines) {
  const lines = noteText.replace(/\s+$/, "").split("\n");
  const i = lines.findIndex((l) => /^## v\S+/.test(l));
  const head = (i === -1 ? lines : lines.slice(0, i)).slice();
  while (head.length && head[head.length - 1] === "") head.pop();
  const tail = i === -1 ? [] : lines.slice(i);
  const parts = [...head, "", ...sectionLines];
  if (tail.length) parts.push("", ...tail);
  return parts.join("\n") + "\n";
}

// --- git wrappers ------------------------------------------------------------

function git(root, args) {
  try {
    return execFileSync("git", args, { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
  } catch (err) {
    if (err && err.code === "ENOENT") {
      throw new ChangelogError("ERROR: git not found on PATH; the changelog command requires git");
    }
    err.git = true; // caller decides how to translate a nonzero exit
    throw err;
  }
}

function tagExists(root, tag) {
  try {
    return git(root, ["tag", "--list", tag]).trim() === tag;
  } catch (err) {
    if (err instanceof ChangelogError) throw err;
    throw new ChangelogError(
      `ERROR: git could not read tags in ${root}; run inside a git checkout with full history and tags (fetch-depth: 0, fetch-tags: true)`,
    );
  }
}

function commitDate(root, tag) {
  return git(root, ["log", "-1", "--format=%cs", tag]).trim();
}

// True when `a` is an ancestor of (or equal to) `b`.
function isAncestor(root, a, b) {
  try {
    git(root, ["merge-base", "--is-ancestor", a, b]);
    return true;
  } catch (err) {
    if (err instanceof ChangelogError) throw err;
    return false;
  }
}

// Commits in `range` (a git revision or "prev..new"), newest first.
function rangeLog(root, range) {
  const raw = git(root, ["log", `--format=%s${US}%b${RS}`, range]);
  return raw
    .split(RS)
    .map((rec) => rec.replace(/^\n+/, ""))
    .filter((rec) => rec.length > 0)
    .map((rec) => {
      const [subject, body = ""] = rec.split(US);
      return { subject: subject.trim(), body: body.trim() };
    });
}

// --- entry -------------------------------------------------------------------

// Generate the changelog section for `release` (a v<version> tag) and prepend it
// to openspec/changelog.md, creating the note when absent. Idempotent no-op when
// the topmost section already names `release`. dryRun prints the section, writes
// nothing. Throws ChangelogError for missing git / unknown tag / unreachable anchor.
export function changelog(root = process.cwd(), { release, dryRun = false } = {}) {
  if (!release) throw new ChangelogError("ERROR: changelog requires --release <tag>");

  const notePath = path.join(root, "openspec", "changelog.md");
  const existing = fs.existsSync(notePath) ? fs.readFileSync(notePath, "utf8") : null;
  const prev = parseAnchor(existing);

  if (prev === release) {
    console.log(`CHANGELOG OK (${release} already recorded; nothing to do)`);
    return { written: false, release };
  }

  if (!tagExists(root, release)) {
    throw new ChangelogError(
      `ERROR: release tag ${release} not found; check out full history with tags (fetch-depth: 0, fetch-tags: true)`,
    );
  }
  if (prev) {
    if (!tagExists(root, prev)) {
      throw new ChangelogError(
        `ERROR: anchor tag ${prev} (topmost changelog heading) not found; check out full history with tags (fetch-depth: 0, fetch-tags: true)`,
      );
    }
    if (isAncestor(root, release, prev)) {
      throw new ChangelogError(
        `ERROR: release tag ${release} is not newer than the anchor ${prev}; nothing to record`,
      );
    }
  }

  const date = commitDate(root, release);
  const range = prev ? `${prev}..${release}` : release;
  const commits = rangeLog(root, range);
  const section = renderSection(release, date, commits, archiveIndex(root));
  const next = prependSection(existing ?? EMPTY_NOTE, section);

  if (dryRun) {
    console.log(section.join("\n"));
    console.log(`CHANGELOG (dry-run, openspec/changelog.md not written)`);
    return { written: false, release, section: section.join("\n") };
  }

  fs.mkdirSync(path.dirname(notePath), { recursive: true });
  fs.writeFileSync(notePath, next);
  console.log(`WROTE openspec/changelog.md (${release})`);
  return { written: true, release };
}
