// Generate one named "hub" note per active change at openspec/changes/<id>.md so
// each change renders as a single labeled anchor (its basename is the change id)
// in Obsidian's graph, doubling as a landing page (task progress + artifact links).
// Opt-in: only this command creates hub notes; deterministic and idempotent, with
// self-scoped stale cleanup. Computed from the vault with node:fs, no OpenSpec CLI.
// Pure helpers are exported for tests; bin/cli.mjs dispatches hubs().

import fs from "node:fs";
import path from "node:path";

export class HubsError extends Error {}

const byKey = (key) => (a, b) => (a[key] < b[key] ? -1 : a[key] > b[key] ? 1 : 0);

// Task counts for a change's tasks.md. Mirrors archive.taskState's completion
// rule (>=1 done and zero open); duplicated per module by convention.
function taskProgress(tasksPath) {
  if (!fs.existsSync(tasksPath)) return { done: 0, open: 0, total: 0, complete: false };
  const t = fs.readFileSync(tasksPath, "utf8");
  const done = (t.match(/- \[x\]/gi) || []).length;
  const open = (t.match(/- \[ \]/g) || []).length;
  return { done, open, total: done + open, complete: done >= 1 && open === 0 };
}

// True iff `text`'s frontmatter region declares `type: hub`. Scans only the
// region between the leading fence and its closer, never YAML-parsed.
function hubMarked(text) {
  const lines = text.split("\n");
  if (lines[0] !== "---") return false;
  for (let i = 1; i < lines.length; i++) {
    if (lines[i] === "---") return false;
    if (lines[i].trim() === "type: hub") return true;
  }
  return false;
}

// Discover active changes under openspec/changes (excluding archive/). Returns
// one record per change with task progress and which linkable artifacts exist,
// sorted by id for deterministic output.
export function collectHubs(root) {
  const changesDir = path.join(root, "openspec", "changes");
  const out = [];
  if (!fs.existsSync(changesDir)) return out;
  for (const ent of fs.readdirSync(changesDir, { withFileTypes: true })) {
    if (!ent.isDirectory() || ent.name === "archive") continue;
    const id = ent.name;
    const dir = path.join(changesDir, id);
    const prog = taskProgress(path.join(dir, "tasks.md"));
    const specsDir = path.join(dir, "specs");
    const deltaCaps = fs.existsSync(specsDir)
      ? fs
          .readdirSync(specsDir, { withFileTypes: true })
          .filter((d) => d.isDirectory() && fs.existsSync(path.join(specsDir, d.name, "spec.md")))
          .map((d) => d.name)
          .sort()
      : [];
    out.push({
      id,
      done: prog.done,
      open: prog.open,
      total: prog.total,
      complete: prog.complete,
      hasProposal: fs.existsSync(path.join(dir, "proposal.md")),
      hasDesign: fs.existsSync(path.join(dir, "design.md")),
      hasTasks: fs.existsSync(path.join(dir, "tasks.md")),
      deltaCaps,
    });
  }
  out.sort(byKey("id"));
  return out;
}

function progressLine(hub) {
  if (hub.total === 0) return "no tasks";
  return `${hub.done}/${hub.total} tasks, ${hub.complete ? "complete" : "in progress"}`;
}

// Render a hub note from a collectHubs record. Deterministic: identical input
// yields byte-identical output. Links use the same vault-relative path-wikilink
// form with display labels as backfill's frontmatter (one direction: hub -> art).
export function renderHub(hub) {
  const { id, deltaCaps } = hub;
  const capTags = deltaCaps.map((c) => `, capability/${c}`).join("");
  const out = [
    "---",
    "type: hub",
    `change: ${id}`,
    `tags: [openspec, type/hub${capTags}]`,
    `aliases: ["${id} hub"]`,
    "---",
    "",
    `# ${id}`,
    "",
    "<!-- Generated by `openspec-obsidian hubs`. Re-run to refresh; do not edit by hand. -->",
    "",
    `**Progress:** ${progressLine(hub)}`,
    "",
    "## Artifacts",
    "",
  ];
  const links = [];
  if (hub.hasProposal) links.push(`- [[changes/${id}/proposal|${id} proposal]]`);
  if (hub.hasDesign) links.push(`- [[changes/${id}/design|${id} design]]`);
  if (hub.hasTasks) links.push(`- [[changes/${id}/tasks|${id} tasks]]`);
  for (const c of deltaCaps) links.push(`- [[changes/${id}/specs/${c}/spec|${id} ${c} delta]]`);
  if (links.length === 0) out.push("_No artifacts._");
  else out.push(...links);
  return out.join("\n") + "\n";
}

// Write one hub note per active change at openspec/changes/<id>.md and delete any
// stale hub note (a changes/*.md whose frontmatter is `type: hub`) whose change
// directory no longer exists. Non-hub notes are never touched. Returns
// { written, removed } (openspec-relative posix paths). dryRun writes nothing.
export function hubs(root = process.cwd(), { dryRun = false } = {}) {
  const openspecDir = path.join(root, "openspec");
  if (!fs.existsSync(openspecDir)) {
    throw new HubsError(`ERROR: no openspec/ directory under ${root}`);
  }
  const changesDir = path.join(openspecDir, "changes");
  const written = [];
  const removed = [];

  for (const hub of collectHubs(root)) {
    const rel = `changes/${hub.id}.md`;
    if (dryRun) {
      console.log(`HUB openspec/${rel} (dry-run, not written)`);
    } else {
      fs.writeFileSync(path.join(changesDir, `${hub.id}.md`), renderHub(hub));
      console.log(`WROTE openspec/${rel}`);
    }
    written.push(rel);
  }

  if (fs.existsSync(changesDir)) {
    const mdFiles = fs
      .readdirSync(changesDir, { withFileTypes: true })
      .filter((e) => e.isFile() && e.name.endsWith(".md"))
      .map((e) => e.name)
      .sort();
    for (const name of mdFiles) {
      const base = name.slice(0, -3);
      const dirPath = path.join(changesDir, base);
      if (fs.existsSync(dirPath) && fs.statSync(dirPath).isDirectory()) continue;
      const filePath = path.join(changesDir, name);
      if (!hubMarked(fs.readFileSync(filePath, "utf8"))) continue;
      const rel = `changes/${name}`;
      if (dryRun) {
        console.log(`HUB openspec/${rel} (dry-run, would remove)`);
      } else {
        fs.rmSync(filePath);
        console.log(`REMOVED openspec/${rel}`);
      }
      removed.push(rel);
    }
  }

  if (!dryRun && written.length === 0 && removed.length === 0) {
    console.log("HUBS OK (no active changes; nothing to write or remove)");
  }
  return { written, removed };
}
